name: Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup C++ environment
      uses: actions/setup-cpp@v1
      with:
        compiler-version: 'latest'

    - name: Install dependencies
      run: sudo apt-get install -y cmake

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: ./build/example
